create table if not exists branches (
    id bigint generated by default as identity primary key,
    name text not null,
    code text not null unique,
    created_at timestamptz not null default now()
);

create table if not exists business_settings (
    id bigint generated by default as identity primary key,
    business_name text not null,
    tax_id text,
    currency_code text not null default 'CLP',
    tax_rate numeric(5, 4) not null default 0.1900 check (tax_rate >= 0),
    created_at timestamptz not null default now()
);

create table if not exists customers (
    id bigint generated by default as identity primary key,
    document_number text unique,
    first_name text,
    last_name text,
    email text,
    phone text,
    created_at timestamptz not null default now()
);

create table if not exists staff_users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    first_name text not null,
    last_name text not null,
    email text,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists categories (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique,
    created_at timestamptz not null default now()
);

create table if not exists products (
    id bigint generated by default as identity primary key,
    category_id bigint references categories(id),
    name text not null,
    description text,
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists attributes (
    id bigint generated by default as identity primary key,
    name text not null,
    slug text not null unique
);

create table if not exists attribute_values (
    id bigint generated by default as identity primary key,
    attribute_id bigint not null references attributes(id) on delete cascade,
    value text not null,
    unique (attribute_id, value)
);

create table if not exists product_attributes (
    product_id bigint not null references products(id) on delete cascade,
    attribute_id bigint not null references attributes(id) on delete cascade,
    primary key (product_id, attribute_id)
);

create table if not exists product_variants (
    id bigint generated by default as identity primary key,
    product_id bigint not null references products(id) on delete cascade,
    sku text not null unique,
    barcode text unique,
    sale_price numeric(12, 2) not null,
    cost_price numeric(12, 2),
    is_active boolean not null default true,
    created_at timestamptz not null default now()
);

create table if not exists variant_attribute_values (
    variant_id bigint not null references product_variants(id) on delete cascade,
    attribute_value_id bigint not null references attribute_values(id) on delete cascade,
    primary key (variant_id, attribute_value_id)
);

create table if not exists inventory (
    id bigint generated by default as identity primary key,
    branch_id bigint not null references branches(id) on delete cascade,
    variant_id bigint not null references product_variants(id) on delete cascade,
    quantity integer not null default 0 check (quantity >= 0),
    minimum_quantity integer not null default 0 check (minimum_quantity >= 0),
    location text,
    unique (branch_id, variant_id)
);

create table if not exists inventory_movements (
    id bigint generated by default as identity primary key,
    branch_id bigint not null references branches(id),
    variant_id bigint not null references product_variants(id),
    staff_user_id bigint references staff_users(id),
    movement_type text not null check (movement_type in ('purchase', 'sale', 'return', 'adjustment', 'loss')),
    quantity_delta integer not null check (quantity_delta <> 0),
    reason text,
    reference text,
    created_at timestamptz not null default now()
);

create table if not exists sales (
    id bigint generated by default as identity primary key,
    branch_id bigint not null references branches(id),
    customer_id bigint references customers(id),
    staff_user_id bigint references staff_users(id),
    sold_at timestamptz not null default now(),
    subtotal numeric(12, 2) not null check (subtotal >= 0),
    tax numeric(12, 2) not null default 0 check (tax >= 0),
    total numeric(12, 2) not null check (total >= 0),
    status text not null default 'completed' check (status in ('completed', 'voided', 'refunded'))
);

create table if not exists sale_items (
    id bigint generated by default as identity primary key,
    sale_id bigint not null references sales(id) on delete cascade,
    variant_id bigint references product_variants(id),
    product_name text not null,
    sku text not null,
    quantity integer not null check (quantity > 0),
    unit_price numeric(12, 2) not null check (unit_price >= 0),
    line_total numeric(12, 2) not null check (line_total >= 0)
);

create table if not exists payments (
    id bigint generated by default as identity primary key,
    sale_id bigint not null references sales(id) on delete cascade,
    method text not null check (method in ('cash', 'debit', 'credit', 'transfer', 'other')),
    amount numeric(12, 2) not null check (amount > 0),
    reference text,
    created_at timestamptz not null default now()
);

create table if not exists returns (
    id bigint generated by default as identity primary key,
    sale_id bigint not null references sales(id),
    branch_id bigint not null references branches(id),
    staff_user_id bigint references staff_users(id),
    reason text,
    total_refunded numeric(12, 2) not null check (total_refunded >= 0),
    created_at timestamptz not null default now()
);

create table if not exists return_items (
    id bigint generated by default as identity primary key,
    return_id bigint not null references returns(id) on delete cascade,
    sale_item_id bigint not null references sale_items(id),
    quantity integer not null check (quantity > 0),
    amount_refunded numeric(12, 2) not null check (amount_refunded >= 0)
);

create index if not exists idx_product_variants_barcode on product_variants(barcode);
create index if not exists idx_sales_sold_at on sales(sold_at);
create index if not exists idx_inventory_variant on inventory(variant_id);
create index if not exists idx_inventory_movements_variant on inventory_movements(variant_id);
