# Generated by Django 5.2.1 on 2026-06-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.IntegerField(choices=[(5, '5 kg'), (11, '11 kg'), (15, '15 kg'), (45, '45 kg')], unique=True)),
                ('llenos', models.IntegerField(default=0)),
                ('vacios', models.IntegerField(default=0)),
                ('conchos', models.IntegerField(default=0)),
                ('precio', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'galones',
            },
        ),
        migrations.CreateModel(
            name='PedidoCentral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cantidad_pedida_llenos', models.IntegerField()),
                ('cantidad_devuelta_vacios', models.IntegerField()),
                ('notas', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pedidos_central',
            },
        ),
    ]
