# Generated by Django 5.2.1 on 2026-06-24 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vendedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galon_peso', models.IntegerField()),
                ('estado_recibido', models.CharField(choices=[('vacio', 'Vacío'), ('concho', 'Concho')], max_length=10)),
                ('cliente_rut', models.CharField(blank=True, default='', max_length=12)),
                ('cliente_nombre', models.CharField(blank=True, default='', max_length=100)),
                ('monto', models.IntegerField()),
                ('metodo_pago', models.CharField(default='efectivo', max_length=20)),
                ('numero_operacion', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vendedores.staffuser')),
            ],
            options={
                'db_table': 'recargas',
            },
        ),
    ]
