# Generated by Django 5.2.1 on 2026-07-01 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recarga',
            name='numero_operacion',
        ),
    ]
