# Generated by Django 5.2.1 on 2026-07-06 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_venta_flujo_local_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='recarga',
            name='metodo_pago_2',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('debito', 'Débito'), ('transferencia', 'Transferencia'), ('credito', 'Crédito'), ('bono_gobierno', 'Bono del gobierno'), ('vale_fisico', 'Vale físico'), ('vale_digital', 'Vale digital')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='recarga',
            name='monto_pago_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recarga',
            name='monto_pago_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='recarga',
            name='pago_mixto',
            field=models.BooleanField(default=False),
        ),
    ]
