# Generated by Django 5.2.1 on 2026-06-24 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galon_peso', models.IntegerField()),
                ('tipo', models.CharField(choices=[('robo', 'Robo'), ('perdida', 'Pérdida'), ('rotura', 'Rotura'), ('otro', 'Otro')], max_length=20)),
                ('cantidad', models.IntegerField()),
                ('notas', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'ajustes_inventario',
            },
        ),
    ]
